### ISSUE TITLE
Ve výsledcích se sice objevily šipky pro určení pořadí při shodě, ale nic nedělají

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#100]
Moc díky za vážně dobře vypadající systém šipek pro určení pořadí osob ve výsledích při shodě počtu hlasů. Ale reálně klikání na šipky pořadí lidí nijak nezmění :-/ Je to vidět teď v aktuální testovací instanci na https://volby.skaut.cz, kde skončily volby, ale nelze šipkami nic změnit.

![image](https://user-images.githubusercontent.com/10085719/92413174-2b562e00-f14f-11ea-8984-92e8eac4619b.png)

Takže šipky jsou zobrazeny správně, ale po kliknutí na zelenou či červenou šipku se jen stránka obnoví, ale k reálné změně pořadí nedojde. 

Prosím o kontrolu a opravu funkčnosti.

**Comment by jan-stanek** [comment]
Problém bude nejspíš v tom, že je tam přidaný nový sloupec, který ale neobsahuje správné hodnoty (nastavují se při načítání kandidátů ze skautIS)

**Comment by jan-stanek** [comment]
@jerrysohn můžeš tam prosím spustit tenhle dotaz: `update candidate set order_correction = id`

pak by to mělo začít fungovat, měl jsem ho přidat už do migrace...

**Comment by jerrysohn** [comment]
@sinacek prosím, spustíš tam ten SQL dotaz, jak píše @jan-stanek, aby se to srovnalo? Abychom teď ověřili funkčnost. Kompletní vymazání všeho v DB a nové načtení od začátku budu dělat až později až zase v další fázi testování po doplnění zbývajících funkcí systému (ať to nemusím testovat a naklikávat stále vše dokola). Díky

**Comment by sinacek** [comment]
omlouvam se, prehledl jsem diskuzi, nyní jsem to uz nastavil

**Comment by jerrysohn** [comment]
Díky, teď už to ruční nastavení pořadí při shodě hlasů funguje dobře. A je to vážně super!
