### ISSUE TITLE
Po ruční změně pořadí u náčelníků se nezmění "vyřazení" zvolených náčelníků z běžných členů

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#102]
Při testování ruční změny pořadí při shodě hlasů jsem narazil na jednu chybku v případě shody hlasů u dvojice náčelní+místonáčelník (stejně by to bylo u mužů). Pokud mají shodu a musím ručně určit, kdo vyhrál, tak tato změna pak neprovede vyškrtnutí té vítězné dvojice z výsledků členek (členů) Náčelnictva. 

Je to sice trochu teoretický problém, protože spíš nepředpokládám, že by se objevili na poslední chvíli další protikandidáti na náčelníky, ale přijde mi, že když už ten systém takhle tvoříme, bylo by fajn mít vyladěn i tento detail.

Bylo by možné na to ještě mrknout?

**Comment by jan-stanek** [comment]
zvláštní, tohle jsem taky testoval, kouknu na to

**Comment by jan-stanek** [comment]
Nemám s tím problém
Před prohozením:
![Screenshot_2020-09-10 Nastavení](https://user-images.githubusercontent.com/11959693/92762363-d0147d80-f392-11ea-8223-c7c78e3663a1.png)

Po prohození náčelních i náčelníků:
![Screenshot_2020-09-10 Nastavení(1)](https://user-images.githubusercontent.com/11959693/92762445-e3bfe400-f392-11ea-8cdf-7a695ec6fbb8.png)

Jediné co mě napadá, jestli tam nemůže být nějaká cache na výsledek dotazu. Pořadí se ani nikam neukládá, vyhodnocuje se při každém zobrazení, jen je tam řazení podle 2 sloupců - hlasů a korekčního sloupce

**Comment by sinacek** [comment]
zkousel jsem to tedka na volby.skaut.cz a funguje mi to správně. @jerrysohn pokud ti to bude se opakovat, tak to znovu otevři
