### ISSUE TITLE
Po uplynutí 3 dnů od vyhlášení výsledků zobrazovat na stránce námitek hlášku

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#103]
Testoval jsem funkčnost těch námitek a vše je velmi dobře a správně. Jen jsem si všiml, že když uplynou 3 dny od vyhlášení výsledků voleb (je to tedy trochu nafixlované - výsledky vyhlášeny, pak upraven datum publikování aby byl starý, a následně jsem změnil datum voleb "na budoucnost", protože nechci, aby teď byly na webu vidět fiktivní výsledky), tak na té stránce po uplynutí toho času se zobrazí "prázdná stránka" jen s nadpisem.

Prosím, bylo by možné vždy, když je před volbami a také po uplynutí těch 3 dnů po vyhlášení výsledků, tam byla ještě informační hláška pro uživatele, která říká, že námitky lze podávat nejpozději 3 dny po vyhlášení - tedy klidně tu hlášku, co tam už dnes zobrazujeme v době, kdy se námitky podávat dají (z ní je to myslím také pochopitelné).

**Comment by jan-stanek** [comment]
Upravím, ale aktuálně se do systému běžní delegáti přihlási jen v průběhu voleb a v průběhu času na námitky. Takže jestli chceme aby tu hlášku někdy viděli, tak musíme upravit ještě tohle.
