### ISSUE TITLE
Aktualizovat odkazy v textech + oprava title webu

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#105]
Prosím o aktualizaci - doplnění - odkazů v textech na webu.

1) na homepage:
a) odkaz na článek na Křižovatce:
https://krizovatka.skaut.cz/zpravodajstvi/5286-distancni-volby-ustrednich-organu-terminy-zivych-vysilani-dulezite-informace

2) na stránce hlasovacího lístku:
a) odkaz na Směrnici k volbám 2020:
https://krizovatka.skaut.cz/dokumenty/file/2824-smernice-mimoradne-volby
b) odkaz na článek na Křižovatce:
https://krizovatka.skaut.cz/zpravodajstvi/5286-distancni-volby-ustrednich-organu-terminy-zivych-vysilani-dulezite-informace

3) oprava title webu
všiml jsem si, že web má v title všude "Sněm", prosím o opravu na title: "Elektronické volby | Junák - český skaut" a před tím klidně může být vždy název stránky "Námitky | ..." či "Hlasovací lístek | ..." Snad to je snadná úprava.

**Comment by sinacek** [comment]
upraveno a nasazeno
