### ISSUE TITLE
Snaha o stažení kandidátů končí na chybě

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#107]
Chtěl jsem teď udělat další kolo závěrečných testů, ale padlo mi to na snaze o stažení kandidátů (všechny ostatní věci se z testovacího skautISu stáhnout povedlo). Prosím o kontrolu a opravu:
![image](https://user-images.githubusercontent.com/10085719/93242026-793de800-f786-11ea-8098-3b93f3b36873.png)

**Comment by jan-stanek** [comment]
@sinacek nejsou tam nějaká jiná id funkcí?

**Comment by sinacek** [comment]
omylem jsem pri promazavani smazal i seznam funkci kandidatu, jiz jsou zpet a vse funguje
