### ISSUE TITLE
Oprava překlepu

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#108]
V rámci zobrazení upozornění na maximální možný počet osob k zaškrtnutí (červená hláška s vykřičníkem, co vyskočí) obsahuje překlep, chybí tam písmeno "m" ve slově "maximálně" (je to i u těch dalších validačních hlášek).
![image](https://user-images.githubusercontent.com/10085719/93379784-9a720780-f85e-11ea-999e-dd3f0ae40595.png)

Pak je ještě překlep v té validační hlášce u první volby "náčelní + místonáčelní", ve validační hlášce je u prvního slova na konci "k", jako by šlo o muže (náčelník a místonáčelní), má být správně "náčelní a místonáčelní"

**Comment by jerrysohn** [comment]
A pak ještě tady chybí čárky ve větě: 
![image](https://user-images.githubusercontent.com/10085719/93380870-1f115580-f860-11ea-8c6f-2c48457d2154.png)

Má být:
Tip: Další informace k elektronickým volbám v roce 2020, a vše co s tím souvisí, najdete ...

**Comment by sinacek** [comment]
opraveno https://github.com/skaut/snem-volby/commit/7142159e576b7d3d457b00806cb9160e797b62d8
