### ISSUE TITLE
Odkazy na články a předpisy odkazovat do nové záložky

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#109]
Ještě se v testování objevila docela dobrá prosba, aby odkazy (na homepage i v rámci stránky s informacemi k hlasování) měla všechny odkazy nastavené s otvíráním do nové záložky. Prosím tedy o nastavení k odkazu atributu target="_new" (je pravda, že pokud na to někdo klikne, tak se dostane na jinou stránku a nerad bych, abychom měli "zmatené delegáty", kteří nebudou vědět jak zpět/kde hlasovat)

**Comment by sinacek** [comment]
nasazeno https://github.com/skaut/snem-volby/commit/2ed80487fd9e461286e5d081319703dc5ead9683
