### ISSUE TITLE
Po vyhlášení (zveřejnění) výsledků voleb skrýt v nastavení tlačítka pro změnu pořadí

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#110]
Ještě jsem si všiml, že po té, co komise zveřejní výsledek voleb, tak se na stránce "Nastavení" stále zobrazují tlačítka šipek pro posun kandidátů, co dostaly stejný počet hlasů. Úplně správně by bylo ta tlačítka po zveřejnění výsledků skrýt, ať to tam vizuálně "nedráždí".

**Comment by jan-stanek** [comment]
Tohle by tam mělo být, nezmizí to po reloadu? Možná to zveřejnění nedělá reload celé stránky.

**Comment by jerrysohn** [comment]
jo, opravdu je potřeba reload stránky. což je matoucí v tom, že se dole objeví datum, že výsledky byly vyhlášeny, ale nahoře nad tím jsou stále vidět ta tlačítka. Tak jestli tím kliknutím na vyhlášení rovnou raději neudělat refresh stránky.

**Comment by jan-stanek** [comment]
upravím
