### ISSUE TITLE
Komponenta hlasovácí lístek

### ISSUE THREAD

**Issue by sinacek** [skaut/snem-volby#72]
Dle načtených delegátů #69 se vytvoří hlasovací lístek.

Hlasovací lístek musí vždy obsahovat i možnost chci nehlasovat v této kategorii.

a) volba náčelní a místonáčelní - 1 dvojice
b) volba náčelníka a místonáčelníka - 1 dvojice
c) volba členů a členek Náčelnictva - 5 žen + 5 mužů
d) volba členů Ústřední revizní komise - 7 osob
e) volba členů Rozhodčí a smírčí rady - 5 osob

Nedovolí hlasovat pro více, ale může být zaškrtnuto i méně (dokonce i nikdo)

**Neukládá se vazba delegát a konktétní hlas!**

**Comment by jan-stanek** [comment]
Aby se neukládala vazba mezi delegátem a hlasem, tak buď nemůžeme ukládat čas u hlasu, nebo u delegáta, kde ho chceme mít?

**Comment by sinacek** [comment]
Nechal bych ho u delegáta
