### ISSUE TITLE
Změny v zobrazování stavu VotingStateBox

### ISSUE THREAD

**Issue by sinacek** [skaut/snem-volby#73]
Informace o přihlášení delegátů #71 se bude zobrazovat i v komponentě na průběžné zobrazení pro komisi. Tedy upravit https://github.com/skaut/snem-volby/blob/master/app/Components/VotingStateBox.php 

Pokud by **nebyla účast** (stačí se přihlásit, není nutné odevzdat hlasovací lístek) alespoň 50 %, tak se bude zobrazovat, že jsou volby neplatné a budou se muset později v novém termínu opakovat. Zde je pak možné toto pouze zveřejnit, ale není možné se podívat na počty hlasů.

### Pokud je počet přihlášených nad 50%

- seznam kandidátů do jednotlivých funkcí (asi podobně jako na hlasovacím lístku) a u toho i počet hlasů pro jednotlivé osoby
- pro každou sekcí (voleným orgánem) bude souhrn kolik “hlasovacích lístků bylo odevzdáno”

Pak bude vyznačeno, kdo je vlastně zvolen a to dle pravidel:
1) dle počtu odevzdaných hlasů;
2) pro zvolení je potřeba alespoň 1 hlas, kdo by žádný nedostal je označen “nezvolen”;
3) označí se “zvolen” a “náhradník” dle pořadí a toho, kolik se volí do jakého orgánu osob/dvojic
pokud by u někoho byla shoda v počtu hlasů, musí komise ručně vyznačit pořadí => je závazné uložit informaci o pořadí do výsledků (nestačí jen počet hlasů); při shodě počtu hlasů komise losuje mimo systém o pořadí a pořadí nastaví v systému - přesunuto do samostatného issue #85

**Comment by jan-stanek** [comment]
Chápu to správně takhle?
- v průběhu voleb - zobrazení počtu delegátů, přihlášených delegátů a hlasujících delegátů
- po skončení voleb
  - účast < 50 % - hláška, že volby jsou neplatné + tlačítko pro zveřejnění této hlášky
  - účast >= 50 % - výsledky voleb

Jak budeme řešit tu rovnost hlasů, nějakej formulář, kde komise označí, kdo byl zvolen?

**Comment by sinacek** [comment]
tlačítko na zveřejnění tam již je, tedka jen přibude ta možnost druhého stavu. 

Nevím jestli má cenu dělat formulář na rovnost hlasů a nebo to vyřeší jerry v případě potřeby příznakem v databázi, protoze pravděpodobnost že se to použije je malá.

**Comment by jan-stanek** [comment]
Podle odpovědi do Jerryho ve slacku je třeba tam tu možnost na změnu pořadí mít, třeba jako šipky na přesunutí.

Přesouvání umí i ublaboo datagrid, ale nevím jestli by nám to fungovalo, když nepoužíváme všechny jejich javascripty, případně tam jen dát tlačítka nahoru/dolů
