### ISSUE TITLE
Informace o delegátech pro komisi

### ISSUE THREAD

**Issue by sinacek** [skaut/snem-volby#74]
Mimořádná komise si může zobrazit:
- počty oprávněných delegátů
- informaci kolik jich hlasovalo
- může si zobrazit i seznam delegátů (jméno, příjmení, příp. přezdívka, zda jsou z funkce nebo za jakou OJ - ev.č.+název) a v něm informaci, zda se osoba účastnila voleb a informaci, zda osoba hlasovala (tedy budou mít možnost i v případě potřeby spočítat “prezenčku”, že sedí s tím číslem lidí, kolik mohlo hlasovat a kolik hlasovací lístky odevzdalo

**Comment by jan-stanek** [comment]
Informace o počtu oprávněných delegátů a informace o hlasování bude součástí #73

**Comment by jerrysohn** [comment]
Tabulka se seznamem delegátů vypadá a zobrazuje věci dobře. Děkuji za to.

Ale všiml jsem si, že nezobrazuje dole počet těch "ano" na konci tabulky:
![image](https://user-images.githubusercontent.com/10085719/92234115-c3cf8280-eeb1-11ea-99cb-5286d96ce4be.png)

(zkouším to ještě v době probíhajících voleb, ale tohle by mělo zobrazovat jako číslo ke kontrole kdykoli během voleb i po nich)

Prosím o opravu

**Comment by jan-stanek** [comment]
Vyzkoušel jsem a součty tam mám, zamerguju to ať se posuneme dál a kdyby s tím byl pořád problém, tak uděláme samostatné issue
