### ISSUE TITLE
Ruční úprava pořadí v případě shody hlasů

### ISSUE THREAD

**Issue by sinacek** [skaut/snem-volby#85]
přebráno z #73 

pokud by u někoho byla shoda v počtu hlasů, musí komise ručně vyznačit pořadí => je závazné uložit informaci o pořadí do výsledků (nestačí jen počet hlasů); při shodě počtu hlasů komise losuje mimo systém o pořadí a pořadí nastaví v systému

**Comment by jerrysohn** [comment]
Představoval bych si to tak, že komise bude po konci voleb mít možnost v té správě se podívat, jak dopadly volby (vidí počty hlasů). A u všech osob na danou funkci, které mají shodný počet hlasů by se objevily třeba šipky či tak něco a bylo možné posunout pořadí, aby bylo jasně určeno, jaké to pořadí je, i když počet hlasů měli stejně (komise to bude nějakým spravedlivým a průkazným systémem rozhodovat mimo systém a do něj pak jen zadá to pořadí).
A toto pořadí bude potřeba určit u všech shodných počtů hlasů - tedy jak u těch, kteří se tím stávají zvolení (vešli se do maximálního voleného počtu osob), tak i ti na pozicích náhradníků (protože, kdyby někdo v budoucnu odstoupil, je nutné vědět, jaké bylo pořadí a kdo z náhradníků nastupuje). Jediné, kde by to nebylo nutné, je u osob, které by nedostaly žádný hlas - ty nejsou vůbec zvolené ani náhradníky a jsou "mimo".
Myslím, že tedy ve výsledcích se musí držet u těch osob nejen sloupec s počtem hlasů, ale i sloupec s pořadím - a podle toho se musí na konci vypsat výsledky, aby bylo jasně vidět, kdo je 1., 2., 3., ...
Žádné speciální texty u toho potřeba nejsou, označení "zvolen/a", "náhradník", "nezvolen/a" je věc, která má být u všech standardně a není potřeba nijak speciálně textovat osoby, které měly stejný počet hlasů a pořadí bylo komisí určeno - to bude prostě vidět z pořadí, jak budou seřazeni a viditelného počtu získaných hlasů.

Seznam výsledků něco jako:

pořadí | jméno osoby | počet hlasů | výsledek
1. | Jan Novák (Jounas)  | 75 | zvolen
2. | Eva Neúspěšná | 75 | náhradník
3. | Pepa Smolař | 0 | nezvolen
