### ISSUE TITLE
Snaha o stažení dat ze skautISu končí chybou

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#91]
Pokud se pokusím na stránce https://volby.skaut.cz/auth/admin/settings kliknout na stažení členů komise, tak to tam (https://volby.skaut.cz/auth/admin/settings?do=saveCommissionMembers) nyní padne do chyby: ServerError

**Comment by jerrysohn** [comment]
Tak to vypadá, že aktuálně na testovací verzi na webu padá veškeré stahování dat ze skautISu.
Padne i snaha o stažení kandidátů a stejně tak snaha o stažení seznamu delegátů.

**Comment by jan-stanek** [comment]
lokálně jsem s tím včera neměl problém, takže to bude asi konfigurací

@sinacek co tam vlastně je za verzi, nasazuje se tam automaticky master, nebo to ještě nefunguje?

**Comment by sinacek** [comment]
padá to jen s debug: false a je to  neco v cache/doctrine

nasazuju to rucne na docker hub a pak automaticky uz na server

**Comment by jan-stanek** [comment]
takže promazání cache to vyřešilo, můžeme uzavřít?

**Comment by sinacek** [comment]
jeste to potrebuju vyzkouset na locale, ktery se bude v produkcnim modu. Případně to pak zkusit overit jestli je to problem jen  v dockeru

**Comment by jan-stanek** [comment]
Párkrát jsem narazil na problém s právy při přepisování .log souborů. Myslím, že se to stává když log soubor vytvoří migrace, asi je to jiný uživatel. Není to ten samej problém?

**Comment by sinacek** [comment]
to bude problém s tou migrací pod jiným uživatelem
