### ISSUE TITLE
Podané námitky zobrazit i roli členů RSRJ

### ISSUE THREAD

**Issue by jerrysohn** [skaut/snem-volby#99]
V návaznosti na #98 se na stránku "Námitky" se zobrazením přehledu podaných námitek navíc kromě "superadminů" budou moci podívat i uživatelé v roli "Ústředí: Rozhodčí a smírčí rada". Ta má ve skautISu (v testovacím i ostrém) jedinečný klíč key=ustrediRSRJ (pro identifikaci role je stejný textový klíč v ostrém i testovacím skautISu; číselné ID se liší, stejně jako se už lišilo u roli pro mimořádnou komisi; pro info - v testovacím skautISu má role RSRJ ID=134 a v ostrém skautISu ID=153; ale textový klíč je právě pro jednoznačnou identifikaci stejný a nazvaný právě "ustrediRSRJ")

**Comment by jerrysohn** [comment]
V testovacím skautISu jsem pak založil i testovacího uživatele, který je v RSRJ a má tam přidanou tuto speciální roli. Přístupové údaje k testování jsou v té on-line tabulce s testovacími uživateli pro Valný sněm / vývoj eVoleb.

**Comment by jan-stanek** [comment]
členové RSRJ můžou být zároveň delegáti? Teď to mám udělané tak, že mají stejně jako admini a komise přístup do systému i před začátkem hlasování -> nevyplní se jim čas prvního přihlášení a musí se pak v průběhu hlasování přihlásit znovu

**Comment by sinacek** [comment]
Mohou a nechal bych to tak. Jen je @jerrysohn poučí

**Comment by jerrysohn** [comment]
@jan-stanek je to jak píše @sinacek, opravdu dojde k poučení členů RSRJ, aby věděli co a jak (stejně jako budu poučovat členy mimořádné volební komise).

**Comment by jan-stanek** [comment]
@jerrysohn u uživatele regina je poznámka, že není delegátem, jen členem RSRJ, ale přijde mi, že delegátem je. Je chyba v poznámce, nebo delegáty špatně poznáváme?

**Comment by jerrysohn** [comment]
@jan-stanek omlouvám se, je to opravdu chyba v té tabulce; Regina je skutečně delegátkou z titulu funkce. Klíčové ale pro tuto funkci má být to, že má tu roli RSRJ (bez ohledu na to, zda je či není delegátkou sněmu).
